Update customizing_cli.md
langium/langium-website pull request #121
Opened 2022-12-29 18:42 UTC by insafuhrmann

Typo fixes and a small wording change (as imho the sentence does not fully fit the example (no ast extraction).

2023-01-11 17:53 UTC, montymxb requested changes
Typo fixes look good, but small suggestion on one sentence.

2023-01-11 17:53 UTC, montymxb commented on hugo/content/tutorials/customizing_cli.md
> +Some amount of the contents for our custom action are shared with the `generateAction` function. This isn't surprising, given that for example we still need to set up our language's services.
I'm on board with dropping the note about extracting the AST. However I would also suggest another slight change to the 2nd sentence, dropping for example and going for a simpler sentence.
```suggestion
Some amount of the contents for our custom action are shared with the `generateAction` function. This isn't surprising given that we still need to set up our language's services.
```

2023-01-13 10:26 UTC, insafuhrmann commented
@montymxb 
Thanks for the review, I committed the requested changes.

2023-01-13 11:17 UTC, montymxb approved these changes
:octocat: approved!

2023-01-13 11:30 UTC, merged

2023-01-13 11:31 UTC, insafuhrmann commented
Thanks @montymxb!